### ISSUE TITLE
Installing pear/net_smtp with composer & --prefer-stable fails

### ISSUE THREAD

**Issue by demon** [pear/Net_SMTP#24] opened 2015-11-11 02:59 UTC
Due to a lack of stable releases for pear/net_socket. 

```
  Problem 2
    - Installation request for pear/net_smtp 1.7.1 -> satisfiable by pear/net_smtp[1.7.1].
    - pear/net_smtp 1.7.1 requires pear/net_socket * -> no matching package found.
```

I know this is technically an issue against pear/net_socket, but issues are disabled there and the project seems mostly unmaintained.

**Comment by alecpl** [comment] 2018-09-09 07:31
@jparise This probably is not a bug anymore, as I see Net_Socket has stable releases. However, how about:
```
"pear/pear-core-minimal": "~1.10",
"pear/net_socket": "~1.2"
```
or `@stable`?

**Comment by jparise** [comment] 2018-09-10 14:49
Yes, it would be nice to close this and move to a newer stable release. Can you send a pull request for this?

**Comment by alecpl** [comment] 2018-09-24 07:00
@jparise This can be closed. How about a new release?

**Closed** 2018-09-25 00:06 UTC

**Comment by jparise** [comment] 2018-09-25 00:32
@alecpl I just released [version 1.8.1](https://github.com/pear/Net_SMTP/releases/tag/1.8.1).

**Comment by alecpl** [comment] 2018-09-25 06:29
@jparise Thank you very much.
